name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch
  push:
    branches:
      - main  # Also trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set the Java version to 11

    - name: Verify Java version
      run: java -version  # Check Java version to ensure it's set to 11

    - name: Install Dependencies (Maven)
      run: mvn install  # Install Maven dependencies

    - name: Run Tests
      run: mvn test  # Run Maven tests

    - name: Upload Test Results
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: test-results
        path: target/test-classes  # Path to store test results

    # Install missing local dependencies (if any)
    - name: Install local dependencies
      run: mvn install:install-file -Dfile=path/to/jacocoagent.jar -DgroupId=com.subayyal -DartifactId=jacocoagent -Dversion=0.8.7 -Dpackaging=jar
