name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch
  push:
    branches:
      - main  # Also trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Java JDK
      uses: actions/setup-java@v4.5.0  # Correct version of setup-java action
      with:
        java-version: '11'  # Set the Java version to 11
        distribution: 'adoptium'  # Correct distribution name for Eclipse Adoptium
        java-package: 'jdk'  # Install JDK package, not JRE
        check-latest: false  # Optional: Prevent checking for the latest version

    - name: Install Dependencies (Maven)
      run: mvn install  # If you're using Maven, this will install dependencies from the pom.xml

    # Optional: If you're using Gradle, replace the Maven command with:
    # - name: Install Dependencies (Gradle)
    #   run: ./gradlew build

    - name: Run Tests
      run: mvn test  # Run the tests using Maven (looks for tests in src/test/java by default)

    # Upload test results (Maven default)
    - name: Upload Test Results (Maven)
      uses: actions/upload-artifact@v3  # Upload test results using the latest version
      with:
        name: test-results
        path: target/test-classes  # Default Maven test results path

    # Optional: If you are using Gradle, you can upload the test results here:
    # - name: Upload Test Results (Gradle)
    #   uses: actions/upload-artifact@v3  # Updated version
    #   with:
    #     name: test-results
    #     path: build/test-results  # Gradle test results path
