name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch
  push:
    branches:
      - main  # Also trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set the Java version to 11 (modify if using a different version)

    - name: Install Dependencies (Maven)
      run: mvn install  # If you're using Maven, this will install dependencies from the pom.xml

    # Optional: If you're using Gradle, replace the Maven command with:
    # - name: Install Dependencies (Gradle)
    #   run: ./gradlew build

    - name: Run Tests
      run: mvn test  # Run the tests using Maven (change to './gradlew test' if using Gradle)

    # Capture and upload test results as artifacts (useful for debugging)
    - name: Upload Test Results (Maven)
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/test-classes  # This is the default location where Maven stores test results

    # Optional: If you are using Gradle, you can upload the test results here:
    # - name: Upload Test Results (Gradle)
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test-results
    #     path: build/test-results  # Default location for Gradle test results
